services:
  - type: web
    name: ucvbot-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r Chatbot-Backend/requirements.txt
    startCommand: python Chatbot-Backend/app.py
    rootDir: Chatbot-Backend
    autoDeploy: true

  - type: web
    name: ucvbot-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build --prefix Chatbot-Frontend
    startCommand: npx http-server Chatbot-Frontend/dist/ -p 3000
    rootDir: Chatbot-Frontend
    autoDeploy: true

  - type: web
    name: ucvbot-chat-java
    env: docker
    region: oregon
    plan: free
    rootDir: ucvbot
    autoDeploy: true
